### PR TITLE
add travis build

### PR DESCRIPTION
**Pull request by brntbeer**
This PR adds a `travis-ci.yml` file to automate running of travis CI for every pull request.

however! Travis will complain that there's no API keys set. So one this PR merges, someone from EasyPost will need to configure some environment variables in the travis profile as described here: https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

### CODE REVIEW

**Comment by richshaffer** [comment]
Hi Brent,

Thanks for this contribution. The current tests are not ideal, as they are using actual API calls. Even though most of them are using a test key, it would still be better if running the tests didn't rely on our API server.

Before we set up Travis CI, I'd like to see if we can mock the API calls with canned responses, possibly with an easy way to update them as the API endpoints are extended. Please give me some time to work on that. I just wanted to let you know what is going on, so you didn't think that we are ignoring this request.

Thanks,

-Richard

**Comment by brntbeer** [comment]
@richshaffer thanks for your response! Happy you took time to do that. I’m new to Go, but if I get some time to look into how other projects do it or coworkers of mine do, should I’ll check back with you or just commit to this branch?

**Comment by richshaffer** [comment]
> I’m new to Go, but if I get some time to look into how other projects do it or coworkers of mine do, should I’ll check back with you or just commit to this branch?

Either action is fine. Thanks!

**Comment by richshaffer** [comment]
Hi Brent. Thanks again for this suggestion and contributing. We went ahead and implemented integration with Travis CI, in a way that doesn't require configure API keys.

Thanks again,

-Richard

**Pull request closed without merging**
